### ISSUE TITLE
spawn_npc guard error

### ISSUE THREAD

**Issue by cwastche** [The-Overlore/lore-machine#90]
Don't know yet how to reproduce, but I sometimes get an error when spawning an npc:

```
2024-03-28 17:54:56,143 - overlore - INFO - Generating new npc profile for realm_entity_id 92
The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `AsyncOpenAiClient.request_prompt_completion() missing 1 required positional argument: 'instructions'`. Make sure that `fn` can be called as a function that takes in a single prompt string and returns a string.
Traceback (most recent call last):
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/llm_providers.py", line 664, in __call__
    result = await self.invoke_llm(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/llm_providers.py", line 840, in invoke_llm
    output = await self.llm_api(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncOpenAiClient.request_prompt_completion() missing 1 required positional argument: 'instructions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/jsonrpcserver/async_dispatcher.py", line 37, in call
    result = await method(
             ^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/overlore/jsonrpc/methods/spawn_npc/spawn_npc.py", line 45, in spawn_npc
    return await handle_regular_flow(params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/overlore/jsonrpc/methods/spawn_npc/spawn_npc.py", line 58, in handle_regular_flow
    response = await npc_profile_builder.build_from_request_params(params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/overlore/jsonrpc/methods/spawn_npc/spawn_npc.py", line 86, in build_from_request_params
    npc_profile = await self.request_npc_profile_generation_with_guard(prompt_for_llm_call)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/overlore/jsonrpc/methods/spawn_npc/spawn_npc.py", line 105, in request_npc_profile_generation_with_guard
    _, validated_response, *_ = await self.guard(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/guard.py", line 774, in _call_async
    call = await runner.async_run(call_log=call_log, prompt_params=prompt_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/run/async_runner.py", line 143, in async_run
    raise e
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/run/async_runner.py", line 105, in async_run
    iteration = await self.async_step(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/utils/telemetry_utils.py", line 242, in to_trace_or_not_to_trace
    response = await fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/run/async_runner.py", line 244, in async_step
    raise e
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/run/async_runner.py", line 205, in async_step
    llm_response = await self.async_call(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/utils/telemetry_utils.py", line 242, in to_trace_or_not_to_trace
    response = await fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/run/async_runner.py", line 281, in async_call
    llm_response = await api_fn(prompt.source)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cwastche/Documents/Code/Overlore/lore-machine/.venv/lib/python3.11/site-packages/guardrails/llm_providers.py", line 668, in __call__
    raise PromptCallableException(
guardrails.llm_providers.PromptCallableException: The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `AsyncOpenAiClient.request_prompt_completion() missing 1 required positional argument: 'instructions'`. Make sure that `fn` can be called as a function that takes in a single prompt string and returns a string.
```

**Comment by edisontim** [comment]
This should be fixed, tell me if you see this happening some more

**Comment by edisontim** [comment]
Closed by getting rid of `guardrails-ai`
